services: 
  terraria-server:
    image: hexlo/terraria-server-docker:latest
    container_name: terraria-server
    restart: unless-stopped
    stdin_open: true
    tty: true     
    ports:
      - 7779:7777
    volumes:
      - type: bind
        source: ./Worlds
        target: /root/.local/share/Terraria/Worlds
