version: '3.2'
services: 
  terraria-server:
    # Github mirror: ghcr.io/hexlo/terraria-server-docker:latest
    image: hexlo/terraria-server-docker:latest
    container_name: terraria-server
    restart: unless-stopped
    stdin_open: true
    tty: true     
    ports:
      - 7779:7777
    volumes:
      - type: bind
        source: ./Worlds
        target: /terraria-server/Worlds
    environment:
      - world=/terraria-server/Worlds/newworld.wld
      - password=hello
      - motd="Welcome to my server! :)"
