services: 
  terraria-server:
    # Github mirror: ghcr.io/hexlo/terraria-server-docker:latest
    image: hexlo/terraria-server-docker:latest
    container_name: terraria-server
    restart: unless-stopped
    networks:
      - traefik_net
    stdin_open: true
    tty: true     
    ports:
      - 7779:7777
    volumes:
      - type: bind
        source: ./worlds
        target: /terraria-server/Worlds
    environment:
      - world=/terraria-server/Worlds/newworld.wld
      - password=passworld
      - motd="Welcome to North's server! :)"
    labels:
      com.centurylinklabs.watchtower.enable: true

  terraria-hamlet:
    # Github mirror: ghcr.io/hexlo/terraria-server-docker:latest
    image: hexlo/terraria-server-docker:latest
    container_name: terraria-hamlet
    restart: unless-stopped
    networks:
      - traefik_net
    stdin_open: true
    tty: true     
    ports:
      - 7778:7777
    volumes: 
      - type: bind
        source: ./worlds
        target: /terraria-server/Worlds
    environment:
      - world=/terraria-server/Worlds/The_Hamlet_of_Snatchers.wld
      - password=hamlet
      - motd="Welcome to North's server! :)"
    labels:
      com.centurylinklabs.watchtower.enable: true

  terraria-MasterWorld:
    # Github mirror: ghcr.io/hexlo/terraria-server-docker:latest
    image: hexlo/terraria-server-docker:latest
    container_name: terraria-masterworld
    restart: unless-stopped
    networks:
      - traefik_net
    stdin_open: true
    tty: true
    ports:
      - 7780:7777
    volumes:
      - type: bind
        source: ./worlds
        target: /terraria-server/Worlds
    environment:
      - world=/terraria-server/Worlds/MasterWorld.wld
      - autocreate=2
      - worldname=MasterWorld
      - difficulty=2
      - password=proathlete
      - motd="Welcome to North's server! :)"
    labels:
      com.centurylinklabs.watchtower.enable: true

  terraria-theconstant:
    # Github mirror: ghcr.io/hexlo/terraria-server-docker:latest
    image: hexlo/terraria-server-docker:latest
    container_name: terraria-theconstant
    restart: unless-stopped
    networks:
      - traefik_net
    stdin_open: true
    tty: true     
    ports:
      - 7781:7777
    volumes: 
      - type: bind
        source: ./worlds
        target: /terraria-server/Worlds
    environment:
      - world=/terraria-server/Worlds/TheConstant1.wld
      - autocreate=2
      - worldname=TheConstant1
      - difficulty=1
      - seed=theconstant
      - password=const
      - motd="Welcome to North's server! :)"
    labels:
      com.centurylinklabs.watchtower.enable: true

  terraria-labor:
    # Github mirror: ghcr.io/hexlo/terraria-server-docker:latest
    image: hexlo/terraria-server-docker:1.4.4-test
    container_name: terraria-labor
    restart: unless-stopped
    networks:
      - traefik_net
    stdin_open: true
    tty: true     
    ports:
      - 7783:7777
    volumes:
      - type: bind
        source: ./worlds
        target: /terraria-server/Worlds
    environment:
      - world=/terraria-server/Worlds/labor1.wld
      - autocreate=1
      - worldname=labor
      - difficulty=2
      - password=passworld
      - motd="Welcome to hexlo's server! :)"
    labels:
      com.centurylinklabs.watchtower.enable: true

networks:
  traefik_net:
    external: true
